#
# Copyright (c) 2019 Anthony J. Greenberg
#
# Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
# THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS
# BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER
# IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
# THE POSSIBILITY OF SUCH DAMAGE.
#

#' Fit a Gaussian mixture model using variational Bayes
#'
#' Quick approximate fit to a Gaussian mixture model using variational Bayes. Missing data are allowed, but no replicate measurements on individuals.
#' The model shrinks small groups to zero if the \code{priorGroupSize} parameter is small.
#' The variational Bayes algorithm sometimes gets stuck in local maxima. It is therefore a good idea to run the model fit several times and pick the "best" result.
#' The \code{nReps} parameter controls the number of replicate runs. The result with the highest value of the deviance information criterion (DIC) is reported as the best.
#'
#' @param data data frame with the data
#' @param traitColumns list of columns in \code{data} that contain trait values
#' @param nGroups number of groups to fit, must be two or greater
#' @param priorGroupSize prior group size; default value 10^-3^
#' @param nReps number of runs to do before picking the best; default value 5
#' @return S3 object of class \code{vbmugamix} that contains a matrix of group means (\code{groupMeans}), a list of within-group covariance matrices (\code{covariances}), a vector of effective group sizes (\code{effNm}), a matrix of group assignment probabilities (\code{p}; individuals in rows groups in columns), and the DIC value (\code{DIC})
#'
#' @export
quickFitModel <- function(data, traitColumns, nGroups, priorGroupSize = 1e-3, nReps = 5) {
	d <- length(traitColumns)
	if (d <= 1) {
		stop("Must have at least two traits")
	}
	yVec <- as.double(unlist(data[, traitColumns]))
	if (nGroups < 2) {
		stop("Must specify more than one group")
	}
	tau0    <- 1.0
	lambda0 <- 1.0
	res     <- NULL
	if (any(is.na(yVec))) {
		yVec[is.na(yVec)] <- NaN
		res <- MuGaMix::vbFitMiss(yVec, d, nGroups, priorGroupSize, tau0, lambda0, nReps)
	} else {
		res <- MuGaMix::vbFit(yVec, d, nGroups, priorGroupSize, tau0, lambda0, nReps)
	}
	res$p           <- matrix(res$p, ncol = nGroups)
	res$groupMeans  <- matrix(res$groupMeans, nrow = nGroups)
	covFac          <- rep(1:nGroups, each = d^2)
	res$covariances <- tapply(res$covariances, covFac, matrix, nrow = d)
	class(res)      <- "vbmugamix"
	return(res)
}

#' Plot variational Bayes population assignments
#'
#' Plot method for MuGaMix objects (generated by \code{quickFitModel()}). Plots population assignment probabilities for each line. Uses \code{data.table} and \code{ggplot2} if available.
#' If the data set contains many lines, their names may not show up well. In such cases, the user can further modify plot parameters by using the plot objects returned by the function.
#'
#' @param obj a \code{vbmugamix} object generated by the \code{quickFitModel} function.
#'
#' @return a plot object (either \code{ggplot} or \code{barplot})
#'
#' @export
plot.vbmugamix <- function(obj) {
	nGrp    <- ncol(obj$p)
	nLn     <- nrow(obj$p)
	indivID <- NULL
	if (is.null(row.names(obj$p))) {
		indivID <- as.character(1:nLn)
	} else {
		indivID <- row.names(obj$p)
	}
	pOrd <- NULL
	if (requireNamespace("data.table", quietly = TRUE)) { # if we have data.table installed
		pOrd <- data.table::as.data.table(obj$p)
		data.table::setnames(pOrd, paste0("G", 1:nGrp))
		data.table::set(pOrd, 1:nLn, "individual", indivID)
		bestGrp <- apply(obj$p, 1, which.max)
		data.table::set(pOrd, 1:nLn, "bestGrp", paste0("G", bestGrp))
		pOrd    <- data.table::melt(pOrd, measure = paste0("G", 1:nGrp), variable.name = "group", value.name = "p")
		pOrd    <- data.table::setorderv(pOrd, c("bestGrp", "p"), c(1, -1))
		indivS  <- factor(unlist(pOrd[, "individual"]), levels = unique(unlist(pOrd[, "individual"])))
		data.table::set(pOrd, 1:nrow(pOrd), "individualS", indivS)
	} else {
		pOrd <- data.frame(p           = array(obj$p),
							individual = indivID,
							bestGrp    = -apply(obj$p, 1, which.max),
							group      = rep(paste0("G", 1:nGrp), each = nLn))
		pOrd <- pOrd[do.call(order, -pOrd[, c("bestGrp", "p")]), ]
		pOrd$individualS <- factor(pOrd$individual, levels = unique(pOrd$individual))
	}
	if (requireNamespace("ggplot2", quietly = TRUE)) {
		return(ggplot2::ggplot(data = pOrd, ggplot2::aes(x = individualS, y = p, fill = group)) + ggplot2::geom_col())
	} else {
		grpMat <- t(obj$p)
		colnames(grpMat) <- indivID
		grpMat <- grpMat[, levels(indivS)]
		return(barplot(grpMat, border = NA, col = rainbow(nGrp), ylab = "p", las = 2))
	}
}
