# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Run the sampler
#'
#' Runs the sampler on the data assuming no fixed effects or missing trait data and one replication level.
#'
#' @param yVec vectorized data matrix
#' @param lnFac factor relating data points to lines
#' @param Npop number of populations
#' @param Nadapt number of adaptation (burn-in) steps
#' @param Nsamp number of sampling steps
#' @param Nthin thinning number
#'
runSampler <- function(yVec, lnFac, Npop, Nadapt, Nsamp, Nthin, Nchains) {
    .Call(`_MuGaMix_runSampler`, yVec, lnFac, Npop, Nadapt, Nsamp, Nthin, Nchains)
}

