# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Variational Bayes model fit
#'
#' Fits a Gaussian mixture model using variational Bayes. Assumes no missing data.
#'
#' @param yVec    vectorized data matrix
#' @param d       number of traits
#' @param nGroups number of groups
#' @param alphaPr prior group size
#' @param sigSqPr prior variance
#' @param covRatio population to error covariance ratio
#' @param nReps   number of model fit attempts before picking the best fit
#' @return list containing group means (\code{groupMeans}), covariances (\code{covariances}), effective group sizes (\code{effNm}), group assignment probabilities (\code{p}), and the deviance information criterion (DIC, \code{DIC}).
#'
#' @keywords internal
#'
vbFit <- function(yVec, d, nGroups, alphaPr, sigSqPr, covRatio, nReps) {
    .Call(`_MuGaMix_vbFit`, yVec, d, nGroups, alphaPr, sigSqPr, covRatio, nReps)
}

#' Variational Bayes model fit with missing data
#'
#' Fits a Gaussian mixture model using variational Bayes. Allows missing data. Missing values should be marked with \code{NaN}.
#'
#' @param yVec     vectorized data matrix
#' @param d        number of traits
#' @param nGroups  number of groups
#' @param alphaPr  prior group size
#' @param sigSqPr  prior variance
#' @param covRatio population to error covariance ratio
#' @param nReps    number of model fit attempts before picking the best fit
#' @return list containing group means (\code{groupMeans}), covariances (\code{covariances}), effective group sizes (\code{effNm}), group assignment probabilities (\code{p}), and the deviance information criterion (DIC, \code{DIC}).
#'
#' @keywords internal
#'
vbFitMiss <- function(yVec, d, nGroups, alphaPr, sigSqPr, covRatio, nReps) {
    .Call(`_MuGaMix_vbFitMiss`, yVec, d, nGroups, alphaPr, sigSqPr, covRatio, nReps)
}

