# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

testLpostLoc <- function(yVec, lnFac, Npop, theta, iSigTheta) {
    .Call(`_MuGaMix_testLpostLoc`, yVec, lnFac, Npop, theta, iSigTheta)
}

lpTestLI <- function(yVec, lnFac, Npop, theta, iSigTheta, ind, limit, incr) {
    .Call(`_MuGaMix_lpTestLI`, yVec, lnFac, Npop, theta, iSigTheta, ind, limit, incr)
}

gradTestLI <- function(yVec, lnFac, Npop, theta, iSigTheta, ind, limit, incr) {
    .Call(`_MuGaMix_gradTestLI`, yVec, lnFac, Npop, theta, iSigTheta, ind, limit, incr)
}

#' Run the sampler
#'
#' Runs the sampler on the data assuming no fixed effects or missing trait data and one replication level.
#'
#' @param yVec vectorized data matrix
#' @param lnFac factor relating data points to lines
#' @param Npop number of populations
#' @param Nadapt number of adaptation (burn-in) steps
#' @param Nsamp number of sampling steps
#' @param Nthin thinning number
#'
runSampler <- function(yVec, lnFac, Npop, Nadapt, Nsamp, Nthin, Nchains) {
    .Call(`_MuGaMix_runSampler`, yVec, lnFac, Npop, Nadapt, Nsamp, Nthin, Nchains)
}

#' Run the sampler with missing data
#'
#' Runs the sampler on the data assuming no fixed effects, but allowing for missing phenotype data, and one replication level.
#' The missingness indicator should have 1 for missing data points and 0 otherwise, however any non-0 value is treated as 1.
#'
#' @param yVec vectorized data matrix
#' @param lnFac factor relating data points to lines
#' @param missIDs vectorized matrix (same dimensions as data) with 1 where a data point is missing and 0 otherwise
#' @param Npop number of populations
#' @param Nadapt number of adaptation (burn-in) steps
#' @param Nsamp number of sampling steps
#' @param Nthin thinning number
#'
runSamplerMiss <- function(yVec, lnFac, missIDs, Npop, Nadapt, Nsamp, Nthin, Nchains) {
    .Call(`_MuGaMix_runSamplerMiss`, yVec, lnFac, missIDs, Npop, Nadapt, Nsamp, Nthin, Nchains)
}

